### ISSUE TITLE
Bot responds to self

### ISSUE THREAD

**Issue by nixylvarie** [RowanHall/traa-hate-sub-warning#1]
The bot responds to its own comments indefinitely.

**Comment by RowanHall** [comment]
Yep. Noticed this [in this thread.](https://www.reddit.com/r/traaaaaaannnnnnnnnns/comments/c223pi/progress_progress_thank_you_mods_of_rdankmemes/).

Commit 23d29159bbbb93643d61fd79a2b4020aa8b86dee fixed this issue.
